#!/bin/sh

SCRIPT=$(readlink -f $0)
BASEDIR=$(dirname $SCRIPT)

NP=$(nproc)



errexit() {
	echo "#############################################"
	echo "Build failed!"
	echo "$1"
	exit 1
}


ptxdist_clean()
{
	cd $BASEDIR/$1
	
	ptxdist -q clean					|| errexit "Error while cleaning $1"
}


ptxdist_build()
{
	cd $BASEDIR/$1
	
	if ! ptxdist images -j$NP; then
		ptxdist images					|| errexit "Error while building $1"
	fi
}



# Clean everything first
ptxdist_clean initramfs
ptxdist_clean root
ptxdist_clean boot


# Now build all images
ptxdist_build initramfs
ptxdist_build root
ptxdist_build boot


echo "#############################################"
echo "Build completed successfully!"

exit 0
