#!/bin/sh

SCRIPT=$(readlink -f $0)
BASEDIR=$(dirname $SCRIPT)


cd $BASEDIR/root
ptxdist -q clean	|| exit 1
ptxdist images		|| exit 1

cd $BASEDIR/boot
ptxdist -q clean	|| exit 1
ptxdist images		|| exit 1

exit 0
