#!/bin/sh

# Copyright (c) 2016 Artur Wiebe <artur@4wiebe.de>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and
# associated documentation files (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


DISKDEV=/dev/sda
SWITCHDEV=/dev/sda2
ROOTDEV=/dev/sda3
DATADEV=/dev/sda4

SWITCHMNT=/mnt/switch
ROOTMNT=/mnt/root
DATAMNT=/mnt/data

UPDATEFILE=$SWITCHMNT/update
DATAFILE=$SWITCHMNT/data


#exec > /var/log/update 2>&1


data_format()
{
echo "appending data partition (using rest of sd-card)"
sfdisk -a $DISKDEV << +++++
-,+,-,-
+++++

sync
sleep 3
blockdev --rereadpt $DISKDEV
sleep 2
}


data_init()
{
echo "running data init"

echo "(re)creating data fs ..."
mkfs.ext4 -Fq -L "DATA" $DATADEV
mount $DATAMNT

echo "initializing data fs ..."
tar -C $DATAMNT -x -f $DATAFILE

sync
rm -f $DATAFILE 
sync

echo "finished data init"	
}


switch_mount() 
{
echo "check and mount switch partition"

fsck.vfat -a $SWITCHDEV
mount $SWITCHMNT

# delete all stubs created by fsck
find $SWITCHMNT -iname "*.REC" -delete
}


update() 
{
echo "running update"

echo "testing update file integrity"
if ! tar -x -O -f $UPDATEFILE &> /dev/null
then
	echo "update file is corrupt -> deleting"
	rm -f $UPDATEFILE
	return 1
fi

echo "(re)creating root fs ..."
mkfs.ext4 -Fq -L "ROOT" $ROOTDEV
mount $ROOTMNT

echo "updating root fs ..."
tar -C $ROOTMNT -x -f $UPDATEFILE

sync
rm -f $UPDATEFILE
sync

echo "finished update"	
}


while [ ! -b $DISKDEV ]; do
	echo "waiting for $DISKDEV ..."
	sleep 1; 
done


if [ ! -b $DATADEV ]; then
	data_format
	REBOOT=yes
fi

switch_mount

if [ -f $DATAFILE ]; then
	data_init
	REBOOT=yes
fi

if [ -f $UPDATEFILE ]; then
	update
	REBOOT=yes
fi


if [ -n "$REBOOT" ]; then
	reboot
fi



########################################
echo "start recovery shell"

echo "mount all filesystems"
mount -a

echo "run rc.d services"
run-parts -a start /etc/rc.d
