#!/bin/sh

SCRIPT=$(readlink -f $0)
BASEDIR=$(dirname $SCRIPT)

NP=$(nproc)

cd $BASEDIR


errexit() {
	echo "#############################################"
	echo "Build failed!"
	echo "$1"
	exit 1
}


ptxdist_build()
{
	ptxdist $1 -q clean					|| errexit "Error while cleaning $1"
	
	if ! ptxdist $1 go -j$NP; then
		ptxdist $1 go					|| errexit "Error while building $1"
	fi
}



# Now build all images
#ptxdist_build "--platformconfig=configs/iMX6/platformconfig --toolchain=/opt/OSELAS.Toolchain-2016.06.1/arm-v7a-linux-gnueabihf/gcc-5.4.0-glibc-2.23-binutils-2.26-kernel-4.6-sanitized/bin"
ptxdist_build "--platformconfig=configs/i586/platformconfig --toolchain=/opt/OSELAS.Toolchain-2016.06.1/i586-unknown-linux-gnu/gcc-5.4.0-glibc-2.23-binutils-2.26-kernel-4.6-sanitized/bin"
ptxdist_build "--platformconfig=configs/i686/platformconfig --toolchain=/opt/OSELAS.Toolchain-2016.06.1/i586-unknown-linux-gnu/gcc-5.4.0-glibc-2.23-binutils-2.26-kernel-4.6-sanitized/bin"


echo "#############################################"
echo "Build completed successfully!"

exit 0
