#!/bin/sh

SCRIPT=$(readlink -f $0)
BASEDIR=$(dirname $SCRIPT)

NP=$(nproc)

cd $BASEDIR


errexit() {
	echo "#############################################"
	echo "Build failed!"
	echo "$1"
	exit 1
}


ptxdist_build()
{
	ptxdist $1 -q clean					|| errexit "Error while cleaning $1"
	
	if ! ptxdist $1 go -j$NP; then
		ptxdist $1 go					|| errexit "Error while building $1"
	fi
}



# Now build all images
#ptxdist_build --platformconfig=configs/iMX6/platformconfig
ptxdist_build --platformconfig=configs/i586/platformconfig
ptxdist_build --platformconfig=configs/i686/platformconfig


echo "#############################################"
echo "Build completed successfully!"

exit 0
