#!/bin/sh

IMG=${1-mc.img}

MNT=/tmp/mc-img
LOOP=$(losetup -f)


sudo sh -c "

	losetup -P $LOOP $IMG							|| exit 1

	mkdir $MNT
	mount ${LOOP}p1 $MNT							|| exit 1

	cp -r ../mc/conf/etc ../mc/conf/root $MNT/

	rm $MNT/usr/bin/.mc
	rm $MNT/etc/init.d/dhclient

	sync
	umount $MNT
	losetup -d $LOOP

" && xz -zv $IMG
