#!/bin/sh

# timeout in seconds before the default boot entry is started
#global.autoboot_timeout=3

# base bootargs
#global.linux.bootargs.base=""


# try boot root, else boot recovery
global.boot.default="root recovery"


# mount switch partition
mkdir -p /mnt/switch
mount /dev/disk0.1 /mnt/switch


# try to boot the update first, else start recovery to apply it
if [ -f /mnt/switch/update ]
then
  global.boot.default="update recovery"
fi

