#!/bin/sh

HOST=${1-sys}
PORT=${2-22}

SCRIPT=$(readlink -f $0)
BASEDIR=$(dirname $SCRIPT)

cd $BASEDIR


if [ "$HOST" = "sys" ]; then 

  ssh \
    -i ssh/id_rsa \
    -p $PORT \
    root@$HOST

else

  ssh \
    -i ssh/id_rsa \
    -p $PORT \
    -o Tunnel=ethernet \
    -w 0 \
    root@$HOST

fi
