#!/bin/sh

HOST=sys

SCRIPT=$0
BASEDIR=$(dirname $SCRIPT)

cd $BASEDIR


ssh -i ssh/id_rsa root@$HOST mount -o remount,rw /																	|| exit 1

scp -i ssh/id_rsa -r ../root/local_src/python-shared/shared root@$HOST:/usr/lib/python3.5/site-packages/			|| exit 1
